apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: brigade-ci
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - configmaps
  - services
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"