trigger:
- master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'
  
  resourceGroupName: 'biceptest'
  location: 'Canada Central'
  templateFile: 'biceptest/test.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: ${ServiceConnectionName}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)
