trigger:
- master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'
  
  ServiceConnection: 'Visual Studio Enterprise (a7b5a8d0-c8df-4fb1-8f6b-9080e188ef57)'
  location: 'canadacentral'
  RGtemplateFile: 'biceptest/resourcegroups.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise (a7b5a8d0-c8df-4fb1-8f6b-9080e188ef57)-1375'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az deployment sub what-if --location $(location) --template-file $(RGtemplateFile)
      az deployment sub create --location $(location) --template-file $(RGtemplateFile)
