trigger:
- *

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  testString: 'Test instance up at:'
  

steps:
- script: |
    echo "Branch ref: $SourceBranch"
    echo "Branch name: $SourceBranchName"
    echo "Source Commit: $SourceVersion"
    echo "Source is a fork?: $PR_IS_FORK"
    echo $PR_ID
    echo $PR_NUMBER
    echo $PR_SOURCE
    echo $PR_SOURCE_URI
    echo $PR_TARGET
    TEST=$(curl -L https://api.github.com/repos/gctools-outilsgc/gcconnex/issues/2496/comments | grep -c "${{ variables.testString }}")
    echo "##vso[task.setvariable variable=prtarget]$TEST"

  env:
    SourceBranch: $(Build.SourceBranch)
    SourceBranchName: $(Build.SourceBranchName)
    SourceVersion: $(Build.SourceVersion)
    PR_IS_FORK: $(System.PullRequest.IsFork)
    PR_ID: $(System.PullRequest.PullRequestId)
    PR_NUMBER: $(System.PullRequest.PullRequestNumber)
    PR_SOURCE: $(System.PullRequest.SourceBranch)
    PR_SOURCE_URI: $(System.PullRequest.SourceRepositoryURI)
    PR_TARGET: $(System.PullRequest.TargetBranch)
  displayName: 'echo vars'

- script: |
    echo ${{ variables.prtarget }}
    echo $TARGET
  condition: and(succeeded(), eq(variables['prtarget'], '0'))
  env:
    TARGET: $(prtarget)
