trigger:
  none

pr:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Branch ref: $SourceBranch"
    echo "Branch name: $SourceBranchName"
    echo "Source Commit: $SourceVersion"
    echo "Source is a fork?: $PR_IS_FORK"
    echo $PR_ID
    echo $PR_NUMBER
    echo $PR_SOURCE
    echo $PR_SOURCE_URI
    echo $PR_TARGET
    TEST=$(curl -L https://api.github.com/repos/Phanoix/brigade-script-testing/issues/15/comments | grep url)
    if [ -z $TEST ]
      then
        echo "##vso[task.setvariable variable=prtarget]something"
    fi
  env:
    SourceBranch: $(Build.SourceBranch)
    SourceBranchName: $(Build.SourceBranchName)
    SourceVersion: $(Build.SourceVersion)
    PR_IS_FORK: $(System.PullRequest.IsFork)
    PR_ID: $(System.PullRequest.PullRequestId)
    PR_NUMBER: $(System.PullRequest.PullRequestNumber)
    PR_SOURCE: $(System.PullRequest.SourceBranch)
    PR_SOURCE_URI: $(System.PullRequest.SourceRepositoryURI)
    PR_TARGET: $(System.PullRequest.TargetBranch)
  displayName: 'echo vars'

- script: |
    echo ${{ variables.prtarget }}
    echo $TARGET
  condition: and(succeeded(), eq(variables['prtarget'], 'something'))
  env:
    TARGET: $(prtarget)
