trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $SourceBranch
    echo $SourceBranchName
    echo $SourceVersion
  env:
    SourceBranch: $(Build.SourceBranch)
    SourceBranchName: $(Build.SourceBranchName)
    SourceVersion: $(Build.SourceVersion)
  displayName: 'echo vars'
