# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Sync azure repo
    git clone --bare https://gctools@dev.azure.com/gctools/gctools-outilsgc/_git/brigade-script-testing.git
    cd brigade-script-testing.git
    git remote add --mirror=fetch upstream https://github.com/Phanoix/brigade-script-testing.git
    git fetch upstream --tags
    B64_PAT=$(echo -n ":$PAT" | base64)
    git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push origin --all
  env:
    PAT: $(PAT)
  displayName: 'Sync repo'
