# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Sync azure repo
    git clone --bare https://gctools@dev.azure.com/gctools/gctools-outilsgc/_git/brigade-script-testing.git
    cd brigade-script-testing.git
    git remote add --mirror=fetch upstream https://github.com/Phanoix/brigade-script-testing.git
    git fetch upstream --tags
    git push origin --all
  displayName: 'Sync repo'
