trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  displayName: TF Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(System.DefaultWorkingDirectory)/TFtest
    backendServiceArm: ${ServiceConnectionName}

- task: TerraformTaskV1@0
  displayName: TF Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(System.DefaultWorkingDirectory)/TFtest
    environmentServiceNameAzureRM: ${ServiceConnectionName}

- task: TerraformTaskV1@0
  displayName: TF Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(System.DefaultWorkingDirectory)/TFtest
    environmentServiceNameAzureRM: ${ServiceConnectionName}
