# This is a basic workflow to help you get started with Actions

name: Sync

on:
  issues:
    types: [opened, edited, labeled, unlabeled, closed, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:  
      - name: GitHub Issues to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@1.6
